version: 0.2

phases:
  install:
    commands:
      - echo "Updating APT packages"
      - apt-get update -y
      
      - echo "Installing Node.js and NPM"
      - curl -sL https://deb.nodesource.com/setup_20.x | bash -
      - apt-get install -y nodejs
      - npm install -g npm@latest --no-color
      - node -v
      - npm -v

      - echo "Installing OWASP Dependency Check"
      - curl -L https://github.com/jeremylong/DependencyCheck/releases/download/v8.3.1/dependency-check-8.3.1-release.zip -o dependency-check.zip
      - apt-get install -y unzip
      - unzip dependency-check.zip -d dependency-check
      - export PATH=$PATH:$(pwd)/dependency-check/bin

      - echo "Installing Snyk CLI via NPM"
      - npm install -g snyk --no-color

      - echo "Installing Snyk to HTML converter"
      - npm install -g snyk-to-html --no-color
      - snyk --version

  pre_build:
    commands:
      - echo "Authenticating with Snyk"
      - snyk auth $SNYK_TOKEN

  build:
    commands:
      - echo "Running Maven Clean and Package"
      - mvn clean package

      - echo "Running OWASP Dependency Check with NVD API Key"
      - mvn org.owasp:dependency-check-maven:check -Dnvd.api.key=$NVD_API_KEY

      - echo "Running Snyk for SAST and Saving Report"
      - snyk test --all-projects --json > snyk-report.json || true

      - echo "Converting Snyk JSON Report to HTML"
      - snyk-to-html -i snyk-report.json -o snyk-report.html

      - echo "Moving Snyk Report to Target Directory"
      - mv snyk-report.html target/

      - echo "Generating image definition file"
      - echo '[{"name":"cicd/test","imageUri":"890742607967.dkr.ecr.ap-south-1.amazonaws.com/cicd/test:latest"}]' > target/imagedefinitions.json

      - echo "Running SonarCloud Analysis"
      - mvn verify sonar:sonar -Dsonar.projectKey=monster -Dsonar.organization=monster -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=9694b8a21216ed240b16f68817210bf76422579f

artifacts:
  files:
    - target/*
    - target/imagedefinitions.json  # Include image definition file

reports:
  dependency-check:
    files:
      - target/dependency-check-report.html
  snyk:
    files:
      - target/snyk-report.html

cache:
  paths:
    - /root/.m2/**/*  # Cache Maven dependencies

post_build:
  commands:
    - echo "Sending Snyk report to S3..."
    - aws s3 cp target/snyk-report.html s3://cicddevsecops/dvja/snyk-report.html

    - echo "Sending OWASP Dependency Check report to S3..."
    - aws s3 cp target/dependency-check-report.html s3://cicddevsecops/dvja/dependency-check-report.html

    - echo "Creating ZIP file for reports..."
    - zip reports.zip target/snyk-report.html target/dependency-check-report.html

    - echo "Sending email notification with reports as attachment..."
    - aws ses send-email --from "vasanth@hts.consulting" --destination "ToAddresses=antony@hts.consulting" --message "Subject={Data=DevSecOps Reports Generated,Charset=utf8},Body={Text={Data='Please find the attached reports for Snyk and OWASP Dependency Check.',Charset=utf8}}" --region "ap-south-1" --attachments "reports.zip"
