version: 0.2

phases:
  install:
    commands:
      - echo "Updating APT packages and installing dependencies"
      - apt-get update -y && apt-get install -y curl unzip jq  # Added jq for parsing JSON

      - echo "Installing Node.js (with npm)"
      - curl -sL https://deb.nodesource.com/setup_20.x | bash - && apt-get install -y nodejs
      - node -v
      - npm -v

      - echo "Installing OWASP Dependency Check CLI"
      - curl -L https://github.com/jeremylong/DependencyCheck/releases/download/v8.3.1/dependency-check-8.3.1-release.zip -o dependency-check.zip
      - unzip dependency-check.zip -d dependency-check
      - export PATH=$PATH:$(pwd)/dependency-check/bin

      - echo "Installing Snyk CLI and Snyk to HTML converter"
      - npm install -g snyk snyk-to-html --no-color
      - snyk --version

  pre_build:
    commands:
      - echo "Authenticating with Snyk"
      - snyk auth $SNYK_TOKEN

  build:
    commands:
      - echo "Running Maven Clean and Package"
      - mvn clean package

      - echo "Running OWASP Dependency Check with NVD API Key"
      - mvn org.owasp:dependency-check-maven:check -Dnvd.api.key=$NVD_API_KEY
      - mv target/dependency-check-report.xml target/dependency-check-report-defectdojo.xml  # Rename for DefectDojo compatibility

      - echo "Running Snyk for SAST and Saving Report"
      - snyk test --all-projects --json > snyk-report.json || true

      - echo "Converting Snyk JSON Report to HTML"
      - snyk-to-html -i snyk-report.json -o snyk-report.html

      - echo "Moving Snyk Report to Target Directory"
      - mv snyk-report.html target/

      - echo "Generating image definition file"
      - echo '[{"name":"cicd/test","imageUri":"890742607967.dkr.ecr.ap-south-1.amazonaws.com/cicd/test:latest"}]' > target/imagedefinitions.json

      - echo "Running SonarCloud Analysis"
      - mvn verify sonar:sonar -Dsonar.projectKey=monster -Dsonar.organization=monster -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=9694b8a21216ed240b16f68817210bf76422579f

  post_build:
    commands:
      - echo "Uploading OWASP Dependency Check Report to DefectDojo"
      - curl -X POST "https://defectdojo.your-instance.com/api/v2/import-scan/" \
        -H "Authorization: Token $DEFECTDOJO_API_KEY" \
        -H "Content-Type: multipart/form-data" \
        -F "scan_type=Dependency Check Scan" \
        -F "file=@target/dependency-check-report-defectdojo.xml" \
        -F "product_name=dvj" \
        -F "engagement=dvja-cicd" \
        -F "scan_date=$(date +%Y-%m-%d)" \
        -F "active=true" \
        -F "verified=true"

      - echo "Uploading Snyk Report to DefectDojo"
      - curl -X POST "https://defectdojo.your-instance.com/api/v2/import-scan/" \
        -H "Authorization: Token $DEFECTDOJO_API_KEY" \
        -H "Content-Type: multipart/form-data" \
        -F "scan_type=Snyk Scan" \
        -F "file=@target/snyk-report.json" \
        -F "product_name=dvja" \
        -F "engagement=dvja-cicd" \
        -F "scan_date=$(date +%Y-%m-%d)" \
        -F "active=true" \
        -F "verified=true"
